---
before_install:
  - >-
    openssl aes-256-cbc
    -K $encrypted_ca86949f853b_key
    -iv $encrypted_ca86949f853b_iv
    -in github_deploy_key.enc
    -out github_deploy_key
    -d
  - chmod 600 github_deploy_key
  - eval $(ssh-agent -s)
  - ssh-add github_deploy_key

install:
  - curl -LO https://github.com/gohugoio/hugo/releases/download/v0.61.0/hugo_0.61.0_Linux-64bit.deb
  - sudo dpkg -i hugo_0.61.0_Linux-64bit.deb

script:
  - hugo

deploy:
  - provider: script
    script: ./bin/publish_to_ghpages.sh
    skip_cleanup: true
    on:
      branch: master
